[book]
authors = ["RM"]
language = "en"
multilingual = false
src = "src"
title = "Python语言程序设计"
[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]
[preprocessor.katex]
after = ["links"]

[output.html]
no-section-label = false

[output.html.fold]
enable = false
level = 1

